"""
Controllability of quantum systems via the dynamical Lie algebra.

A bilinear control system ``H(t) = H_0 + sum_j u_j(t) H_j`` can reach *every* unitary (it is
operator controllable) if and only if the operators ``{-i H_0, -i H_j}`` generate the full Lie
algebra ``su(d)`` (or ``u(d)``) under commutation -- the Lie-algebra rank condition. Starting from
the control generators and repeatedly taking commutators until the set closes gives the *dynamical
Lie algebra* (DLA); its dimension decides controllability:

    dim(DLA) = d^2 - 1  =>  controllable (su(d), traceless generators),
    dim(DLA) = d^2      =>  controllable (u(d)).

This module generates the DLA, reports its dimension, and answers controllability. Verified on the
qubit: ``{X, Z}`` generates ``su(2)`` (dimension 3, since ``[X, Z] ~ Y``) and is controllable, while
a single generator is not.
"""

import numpy as np


def lie_bracket(A, B):
    """The Lie bracket (commutator) ``[A, B] = AB - BA``."""
    A = np.asarray(A, dtype=complex)
    B = np.asarray(B, dtype=complex)
    return A @ B - B @ A


def _real_vec(M):
    """Represent a complex ``d x d`` matrix as a real vector ``[Re, Im]`` for rank computations over
    the real span."""
    M = np.asarray(M, dtype=complex).ravel()
    return np.concatenate([M.real, M.imag])


def _rank(rows, atol=1e-9):
    if not rows:
        return 0
    return int(np.linalg.matrix_rank(np.array(rows), tol=atol))


def lie_closure(generators, max_iter=200, atol=1e-9):
    """
    A basis for the Lie algebra generated by ``generators`` under commutation. Repeatedly adds
    commutators that increase the real rank of the (vectorized) set until it closes. Returns the
    list of independent basis matrices.
    """
    basis = []
    rows = []
    for G in generators:
        G = np.asarray(G, dtype=complex)
        v = _real_vec(G)
        if _rank(rows + [v]) > _rank(rows):
            basis.append(G)
            rows.append(v)
    changed = True
    it = 0
    while changed and it < max_iter:
        changed = False
        it += 1
        current = list(basis)
        for i in range(len(current)):
            for j in range(i + 1, len(current)):
                C = lie_bracket(current[i], current[j])
                if np.allclose(C, 0, atol=atol):
                    continue
                v = _real_vec(C)
                if _rank(rows + [v]) > _rank(rows):
                    basis.append(C)
                    rows.append(v)
                    changed = True
    return basis


def dla_dimension(generators):
    """Dimension of the dynamical Lie algebra generated by ``generators`` (as ``-i H`` are
    proportional to ``H`` for rank purposes, the Hamiltonians themselves may be passed)."""
    return len(lie_closure(generators))


def su_dimension(d):
    """Dimension of ``su(d)``: ``d^2 - 1`` -- the target for full controllability with traceless
    generators."""
    return d * d - 1


def u_dimension(d):
    """Dimension of ``u(d)``: ``d^2``."""
    return d * d


def is_controllable(generators, d):
    """
    True iff the system is operator controllable: the dynamical Lie algebra has dimension
    ``d^2 - 1`` (``su(d)``) or ``d^2`` (``u(d)``) -- i.e. every unitary is reachable.
    """
    dim = dla_dimension(generators)
    return dim == su_dimension(d) or dim == u_dimension(d)


def gate_reachable(generators, d, atol=1e-9):
    """Alias for :func:`is_controllable` phrased for gate synthesis: whether an arbitrary target
    gate can be reached with the given controls."""
    return is_controllable(generators, d)
